[package]
name = "dj-library-gain-calculator"
version = "0.1.0"
authors = ["Paul Adenot <paul@paul.cx>", "Raphaël Lustin <raphael@lustin.fr>"]
edition = "2018"

[dependencies]
audrey = "0.2"
bitflags = "1.2.1"
cfg-if = "0.1"
chrono = "0.4.11"
clap = { version = "2.33.0", features = ["yaml"] }
claxon = "0.4.2"
console = "0.10.0"
directories = "2.0"
ebur128 = "0.1.0"
hound = "3.4.0"
indicatif = "0.14.0"
lazy_static = "1.4.0"
log = "0.4"
parking_lot = { version = "0.10", features = ["serde"] }
quick-xml = { version = "0.17", features = ["serialize"] }
rayon = "1.3"
rmp3 = { version = "0.2", features = ["float"] }
rusqlite = "0.22.0"
serde = { version = "1.0", features = ["derive", "rc"] }
tempdir = "0.3"

[dev-dependencies]
assert_cmd = "0.10"
walkdir = "2"
