[package]
name = "dj-library-gain-calculator"
version = "0.1.0"
authors = ["Paul Adenot <paul@paul.cx>", "Raphaël Lustin <raphael@lustin.fr>"]
edition = "2018"

[dependencies]
audrey = "0.2"
clap = { version = "2.33.0", features = ["yaml"] }
minimp3 = "0.3"
quick-xml = { version = "0.17", features = ["serialize"] }
rayon = "1.3"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
assert_cmd = "0.10"
