[package]
name = "dj-library-gain-calculator"
version = "0.1.0"
authors = ["Raphaël Lustin <raphael@lustin.fr>"]

[dependencies]
clap = { version = "2.33.0", features = ["yaml"] }
quick-xml = { version = "0.17", features = ["serialize"] }
serde = { version = "1.0", features = ["derive"] }
minimp3 = "0.3"
audrey = "0.2"
rayon = "1.3"

[dev-dependencies]
assert_cmd = "0.10"
