on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

name: CI

jobs:
  build:
    name: Build-Test-Format-Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install sqlite3 development package
        run: sudo apt-get update; sudo apt-get install libsqlite3-dev

      - name: Install libxml2
        run: sudo apt-get update; sudo apt-get install libxml2-utils; which xmllint; xmllint --version

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test

      - name: Fmt
        run: cargo fmt

      - name: Clippy
        run: cargo clippy
